correct output of pre-commit and remove comment

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -21,26 +21,26 @@ do
   "$ESLINT" "$FILE"
 
   if [[ "$?" == 0 ]]; then
-    printf "\t\033[32mESLint Passed: $FILE\033[0m"
+    printf "\t\033[32mESLint Passed: $FILE\033[0m\n"
   else
-    printf "\t\033[41mESLint Failed: $FILE\033[0m"
+    printf "\t\033[41mESLint Failed: $FILE\033[0m\n"
     PASS=false
   fi
 done
 
 printf "\nJavascript validation completed!\n"
 
-if ! $PASS; then
-  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains FILESJS that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
-  exit 1
-else
-  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-fi
-
 # Prettify all selected FILESJS
 echo "$FILECODE" | xargs ./node_modules/.bin/prettier --write
 
 # Add back the modified/prettified FILESJS to staging
 echo "$FILECODE" | xargs git add
+
+if ! $PASS; then
+  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains FILESJS that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  exit 1
+else
+  printf "\033[32mCOMMIT SUCCEEDED\033[0m\n"
+fi
 
 exit 0
